Evaluate Paragraph Selection Peformance with CHATGPT

In [40]:
import pandas as pd
import numpy as np
import os
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [60]:
result_dir = os.path.join(os.getcwd(),"classification")
annotated_dir = os.path.join(os.getcwd(),"annotated_csv")

f1_mean = []
for pdf in (os.listdir(result_dir)):

    print(pdf)
    file_path = os.path.join(result_dir, pdf)
    result_df = pd.read_csv(file_path)
    # Define the substring to check for
    substring_to_check = 'No'
    yesstring_to_check = 'Yes'
    # Replace the entire string if it contains the substring, otherwise keep it as it is
    try:
        result_df['classification'] = result_df['classification'].apply(lambda x: 'No' if substring_to_check in x else x)
        result_df['classification'] = result_df['classification'].apply(lambda x: 'Yes' if yesstring_to_check in x else x)

    except:
        pass

    result_df['classification'] = result_df['classification'].map({'Yes': 1, 'No': 0})
    result_df['classification'] = result_df['classification'].fillna(0).astype(int)
    y_pred = result_df["classification"]
    file_path = os.path.join(annotated_dir, pdf[:-4])
    annotated_df = pd.read_csv(file_path)
    annotated_df["Class"] = np.where(annotated_df["Class"] == 11, 1, annotated_df["Class"])
    y_val = annotated_df["Class"]
    print(accuracy_score(y_val, y_pred))
    f1_mean.append(f1_score(y_val, y_pred))
    print(f1_score(y_val, y_pred))
    print(confusion_matrix(y_val, y_pred))

print(f'Chat GPT Val f1: {np.mean(f1_mean):.3f} +- {np.std(f1_mean):.3f}')
    

Al_rabiah, Abdulrahman_Process_2022.pdf.csv.csv
0.9545454545454546
0.2608695652173913
[[354  16]
 [  1   3]]
Campos, Bruno_Detailed_2022.pdf.csv.csv
0.8865384615384615
0.25316455696202533
[[451  55]
 [  4  10]]
Falco, Marcello_Excergettic_2022.pdf.csv.csv
0.9104803493449781
0.19607843137254902
[[412  24]
 [ 17   5]]
Han, Zhenwei_Investigating_2020.pdf.csv.csv
0.9494949494949495
0.37499999999999994
[[185   7]
 [  3   3]]
He, Renchu_Multi_2023.pdf.csv.csv
0.9867021276595744
0.28571428571428575
[[370   1]
 [  4   1]]
Kohler, Andrew_Techno_2021.pdf.csv.csv
0.9216417910447762
0.19230769230769232
[[489  27]
 [ 15   5]]
Martinez, Victor_Conceptual_2023.pdf.csv.csv
0.9616306954436451
0.1111111111111111
[[400   2]
 [ 14   1]]
Muazzam, Yusra_Thermo_2022.pdf.csv.csv
0.9036608863198459
0.32432432432432434
[[457  35]
 [ 15  12]]
Mursics, Joszef_Process_2020.pdf.csv.csv
0.8718535469107551
0.3
[[369  19]
 [ 37  12]]
Chat GPT Val f1: 0.255 +- 0.075
